# Generated by Django 3.2.21 on 2023-10-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20231011_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
